version: '3.8'
name: ibugram

services:
    db:
        build:
            dockerfile: db/Dockerfile
            context: .
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        env_file: .env

    flight:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
        depends_on:
            - db
